// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quran.Data;

namespace Quran.Data.Migrations
{
    [DbContext(typeof(QuranContext))]
    [Migration("20200506225907_AddIndex")]
    partial class AddIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quran.Core.Aya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AyaIndex")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JuzId")
                        .HasColumnType("int");

                    b.Property<int?>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("SurahId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JuzId");

                    b.HasIndex("PageId");

                    b.HasIndex("SurahId");

                    b.ToTable("Ayas");
                });

            modelBuilder.Entity("Quran.Core.Juz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JuzIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Juzs");
                });

            modelBuilder.Entity("Quran.Core.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JuzId")
                        .HasColumnType("int");

                    b.Property<int>("PageIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JuzId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Quran.Core.Surah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<int>("SurahIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Surahs");
                });

            modelBuilder.Entity("Quran.Core.Aya", b =>
                {
                    b.HasOne("Quran.Core.Juz", "Juz")
                        .WithMany()
                        .HasForeignKey("JuzId");

                    b.HasOne("Quran.Core.Page", "Page")
                        .WithMany("Aya")
                        .HasForeignKey("PageId");

                    b.HasOne("Quran.Core.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quran.Core.Page", b =>
                {
                    b.HasOne("Quran.Core.Juz", "Juz")
                        .WithMany()
                        .HasForeignKey("JuzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
